"""empty message

Revision ID: 7c37efc8d6a6
Revises: 
Create Date: 2020-04-24 04:57:54.412591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c37efc8d6a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sname', sa.String(length=64), nullable=True),
    sa.Column('slevel', sa.Integer(), nullable=True),
    sa.Column('verbal', sa.Boolean(), nullable=True),
    sa.Column('somatic', sa.Boolean(), nullable=True),
    sa.Column('material', sa.Boolean(), nullable=True),
    sa.Column('concentration', sa.Boolean(), nullable=True),
    sa.Column('ritual', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spell_sname'), 'spell', ['sname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spell_sname'), table_name='spell')
    op.drop_table('spell')
    op.drop_table('list')
    # ### end Alembic commands ###
